services:
  - type: web
    name: view-avocats-assistant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run talk.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
    plan: free
