[browser]
serverAddress = "talktomeview.streamlit.app"
serverPort = 8501
gatherUsageStats = false

[server]
enableCORS = true
enableXsrfProtection = false

[theme]
base="light"

[client]
toolbarMode = "minimal"

[runner]
fastReruns = true

[logger]
level = "info"
