[theme]
base = "light"
primaryColor = "#1D4E44"

[server]
enableXsrfProtection = false
enableCORS = true

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false

[client]
showErrorDetails = false
toolbarMode = "minimal"
