[server]
enableCORS = true
enableXsrfProtection = false
cors_allowed_origins = ["https://view-avocats.fr", "https://www.view-avocats.fr"]

[browser]
serverAddress = "talktomeview.streamlit.app"
gatherUsageStats = false
